# Generated by Django 5.0.4 on 2024-05-15 05:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('deleted_by', models.UUIDField(null=True)),
                ('concat_fields', models.TextField(unique=True)),
                ('fullname', models.TextField(max_length=100)),
                ('identityCardNumber', models.TextField(max_length=100, unique=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=100)),
                ('maritalStatus', models.CharField(choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'MARRIED'), ('WIDOWER', 'WIDOWER'), ('DIVORCED', 'DIVORCED')], max_length=100)),
                ('birthday', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('deleted_by', models.UUIDField(null=True)),
                ('concat_fields', models.TextField(unique=True)),
                ('entity', models.TextField(default='none', max_length=100)),
                ('permission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('deleted_by', models.UUIDField(null=True)),
                ('concat_fields', models.TextField(unique=True)),
                ('entity', models.TextField(default='none', max_length=100)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
